apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notejam
  name: notejam
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: notejam
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notejam
    spec:
      containers:
      - image: docker.io/batuhanakca/notejam-flask-docker:v1.2-amd64
        imagePullPolicy: IfNotPresent
        name: notejam
        ports:
          - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 15
          timeoutSeconds: 4
          periodSeconds: 5
          failureThreshold: 4
      
        readinessProbe: 
          httpGet:
            path: /readyz
            port: 5000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 5
