apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: notejam-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: notejam
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
