apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: test1-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: test1
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
